<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

    
    <!-- ############## Macros ################## -->
    <!-- ######################################## -->
        
        <xacro:macro name="MiR100_gazebo">

            <gazebo reference="MiR_right_wheel_link">
                <material>Gazebo/DarkGrey</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

            <gazebo reference="MiR_left_wheel_link">
                <material>Gazebo/DarkGrey</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

            <gazebo reference="MiR_fl_caster_rotation_link">
                <material>Gazebo/Grey</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

            <gazebo reference="MiR_fr_caster_rotation_link">
                <material>Gazebo/Grey</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

            <gazebo reference="MiR_bl_caster_rotation_link">
                <material>Gazebo/Grey</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

            <gazebo reference="MiR_br_caster_rotation_link">
                <material>Gazebo/Grey</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

            <gazebo reference="MiR_front_laser_link">
                <material>Gazebo/FlatBlack</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

            <gazebo reference="MiR_back_laser_link">
                <material>Gazebo/FlatBlack</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

            <gazebo reference="MiR_base_link">
                <material>Gazebo/Grey</material>
                <turnGravityOff>false</turnGravityOff>
                <selfCollide>true</selfCollide>
            </gazebo>

        </xacro:macro>

        <xacro:macro name="MiR_controller_plugin_gazebo" params="left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
            <gazebo>
                <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
                    <legacyMode>false</legacyMode>
                    <alwaysOn>true</alwaysOn>
                    <updateRate>1000.0</updateRate>
                    <leftJoint>${left_wheel_joint}</leftJoint>
                    <rightJoint>${right_wheel_joint}</rightJoint>
                    <wheelSeparation>${wheel_separation}</wheelSeparation>
                    <wheelDiameter>${2*wheel_radius}</wheelDiameter>
                    <wheelTorque>10</wheelTorque>
                    <publishTf>1</publishTf>
                    <odometryFrame>map</odometryFrame>
                    <commandTopic>MiR/controller/cmd_vel</commandTopic>
                    <odometryTopic>MiR/controller/odom</odometryTopic>
                    <robotBaseFrame>MiR_footprint</robotBaseFrame>
                    <wheelAcceleration>2.8</wheelAcceleration>
                    <publishWheelJointState>true</publishWheelJointState>
                    <publishWheelTF>false</publishWheelTF>
                    <odometrySource>world</odometrySource>
                    <rosDebugLevel>Debug</rosDebugLevel>
                </plugin>
            </gazebo>
        </xacro:macro>

        <xacro:macro name="set_wheel_friction" params="link friction">
            <gazebo reference="${link}">
                <mu1 value="${friction}"/>
                <mu2 value="${friction}"/>
                <kp value="10000000.0"/>
                <kd value="1.0"/>
                <minDepth>0.01</minDepth>
            </gazebo>
        </xacro:macro>

        <xacro:macro name="p3d_base_controller">
            <gazebo>
                <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>50.0</updateRate>
                <bodyName>MiR_footprint</bodyName>
                <topicName>MiR/pose_ground_truth</topicName>
                <gaussianNoise>0.01</gaussianNoise>
                <frameName>world</frameName>
                <xyzOffsets>0 0 0</xyzOffsets>
                <rpyOffsets>0 0 0</rpyOffsets>
                </plugin>
            </gazebo>
        </xacro:macro>

        <xacro:macro name="MiR100_controller">
            <gazebo>
                <plugin name="ros_control" filename="libgazebo_ros_control.so">
                <robotNamespace>/</robotNamespace>
                <controlPeriod>0.001</controlPeriod>
                <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
                </plugin>
            </gazebo>
        </xacro:macro>



    <gazebo>
      <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
        <robotNamespace>/</robotNamespace>
        <jointName> MiR__base_fl_caster_rotation_joint, MiR__base_fl_caster_wheel_joint,
                    MiR__base_fr_caster_rotation_joint, MiR__base_fr_caster_wheel_joint,
                    MiR__base_bl_caster_rotation_joint, MiR__base_bl_caster_wheel_joint,
                    MiR__base_br_caster_rotation_joint, MiR__base_br_caster_wheel_joint</jointName>
        <updateRate>100.0</updateRate>
        <alwaysOn>true</alwaysOn>
      </plugin>
    </gazebo>

    <!-- ######################################## -->
    <!-- ############## Macros ################## -->





</robot>