<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="mobile_manipulator" >

  <xacro:include filename="$(find mobile_manipulator)/urdf/common.gazebo.xacro" />
  <xacro:include filename="$(find mobile_manipulator)/urdf/mobile_manipulator.gazebo.xacro" />
  <xacro:include filename="$(find mobile_manipulator)/urdf/mobile_manipulator.transmission.xacro" />
  <xacro:include filename="$(find mobile_manipulator)/urdf/sensors.imu.urdf.xacro" />
  <xacro:include filename="$(find mobile_manipulator)/urdf/sensors.sick_s300.urdf.xacro" />
  <xacro:include filename="$(find mobile_manipulator)/urdf/sensors.ultrasound.urdf.xacro" />


<!-- ################# Properties ################ -->
<!-- ############################################# -->

  <!-- ############### MiR ############ -->
  <!-- ################################ -->

    <xacro:property name="deg_to_rad" value="0.017453293" />

    <xacro:property name="mir_100_base_mass" value="58.0" />

    <xacro:property name="mir_100_act_wheel_radius" value="0.0625" />
    <xacro:property name="mir_100_act_wheel_width" value="0.032" />
    <xacro:property name="mir_100_act_wheel_mass" value="1.0" />
    <xacro:property name="mir_100_act_wheel_dx" value="0.037646" />
    <xacro:property name="mir_100_act_wheel_dy" value="0.222604" />

    <xacro:property name="mir_100_caster_wheel_radius" value="${mir_100_act_wheel_radius}" />
    <xacro:property name="mir_100_caster_wheel_width" value="${mir_100_act_wheel_width}" />
    <xacro:property name="mir_100_caster_wheel_mass" value="${mir_100_act_wheel_mass}" />
    <xacro:property name="mir_100_caster_wheel_dx" value="-0.0382" />
    <xacro:property name="mir_100_caster_wheel_dy" value="0" />
    <xacro:property name="mir_100_caster_wheel_dz" value="-0.094" />
    <xacro:property name="mir_100_front_caster_wheel_base_dx" value="0.341346" />
    <xacro:property name="mir_100_back_caster_wheel_base_dx" value="-0.270154" />
    <xacro:property name="mir_100_caster_wheel_base_dy" value="0.203" />
    <xacro:property name="mir_100_caster_wheel_base_dz" value="${mir_100_caster_wheel_radius-mir_100_caster_wheel_dz}" />

    <xacro:property name="imu_stdev" value="0.00017" />
    <xacro:property name="imu_update_rate" value="50" />

  <!-- ################################ -->
  <!-- ############### MiR ############ -->


  <!-- ############### UR10 ############ -->
  <!-- ################################ -->

    <!-- Inertia parameters -->
      <xacro:property name="ur10_base_mass" value="4.0" />  <!-- This mass might be incorrect -->
      <xacro:property name="ur10_shoulder_mass" value="7.778" />
      <xacro:property name="ur10_upper_arm_mass" value="12.93" />
      <xacro:property name="ur10_forearm_mass" value="3.87" />
      <xacro:property name="ur10_wrist_1_mass" value="1.96" />
      <xacro:property name="ur10_wrist_2_mass" value="1.96" />
      <xacro:property name="ur10_wrist_3_mass" value="0.202" />

    <!-- Kinematic model -->
    <!-- Properties from urcontrol.conf -->
      <xacro:property name="d1" value="0.1273" />
      <xacro:property name="a2" value="-0.612" />
      <xacro:property name="a3" value="-0.5723" />
      <xacro:property name="d4" value="0.163941" />
      <xacro:property name="d5" value="0.1157" />
      <xacro:property name="d6" value="0.0922" />

    <!-- link lengths used in model -->
      <xacro:property name="ur10_shoulder_height" value="${d1}" />
      <xacro:property name="ur10_upper_arm_length" value="${-a2}" />
      <xacro:property name="ur10_forearm_length" value="${-a3}" />
      <xacro:property name="ur10_wrist_1_length" value="${d4 - ur10_elbow_offset - ur10_shoulder_offset}" />
      <xacro:property name="ur10_wrist_2_length" value="${d5}" />
      <xacro:property name="ur10_wrist_3_length" value="${d6}" />

    <!-- Arbitrary offsets for shoulder/elbow joints -->
      <xacro:property name="ur10_shoulder_offset" value="0.220941" />  <!-- measured from model -->
      <xacro:property name="ur10_elbow_offset" value="-0.1719" /> <!-- measured from model -->
      <xacro:property name="ur10_upper_arm_inertia_offset" value="0.045" />  <!-- measured from model -->

    <xacro:property name="ur10_shoulder_pan_lower_limit" value="${-pi}"/> 
    <xacro:property name="ur10_shoulder_pan_upper_limit" value="${pi}"/>
    <xacro:property name="ur10_shoulder_lift_lower_limit" value="${-pi}"/> 
    <xacro:property name="ur10_shoulder_lift_upper_limit" value="${pi}"/>
    <xacro:property name="ur10_elbow_joint_lower_limit" value="${-pi}"/>
    <xacro:property name="ur10_elbow_joint_upper_limit" value="${pi}"/>
    <xacro:property name="ur10_wrist_1_lower_limit" value="${-pi}"/>
    <xacro:property name="ur10_wrist_1_upper_limit" value="${pi}"/>
    <xacro:property name="ur10_wrist_2_lower_limit" value="${-pi}"/>
    <xacro:property name="ur10_wrist_2_upper_limit" value="${pi}"/>
    <xacro:property name="ur10_wrist_3_lower_limit" value="${-pi}"/>
    <xacro:property name="ur10_wrist_3_upper_limit" value="${pi}"/>

    <xacro:property name="ur10_safety_limits" value="false"/>
    <xacro:property name="ur10_safety_pos_margin" value="0.15"/>
    <xacro:property name="ur10_safety_k_position" value="20"/>


  <!-- ################################ -->
  <!-- ############### UR10 ############ -->


  <!-- ######## Barrett Hand ########## -->
  <!-- ################################ -->

    <xacro:property name="BH282_joint_damping" value="100.0" />
    <xacro:property name="BH282_joint_friction" value="1.0" />
    <xacro:property name="BH282_joint_effort_limit" value="30.0" />
    <xacro:property name="BH282_joint_velocity_limit" value="2.0" />
    <xacro:property name="BH282_mechanical_reduction" value="1.0" />


  <!-- ################################ -->
  <!-- ######## Barrett Hand ########## -->

<!-- ############################################# -->
<!-- ################# Properties ################ -->


<!-- ################# Macros ################ -->
<!-- ######################################### -->

  <!-- ############### MiR ############ -->
  <!-- ################################ -->
    <xacro:macro name="actuated_wheel" params="locationprefix locationright">
      
      <joint name="MiR__base_${locationprefix}_wheel_joint" type="continuous">
        <origin xyz="0.0 ${-mir_100_act_wheel_dy * locationright} ${mir_100_act_wheel_radius}" rpy="0 0 0" />
        <parent link="MiR_base_link" />
        <child link="MiR_${locationprefix}_wheel_link" />
        <axis xyz="0 1 0" />
        <limit effort="100" velocity="20.0" />
      </joint>

      <link name="MiR_${locationprefix}_wheel_link">
        <xacro:cylinder_inertial mass="${mir_100_act_wheel_mass}" radius="${mir_100_act_wheel_radius}" length="${mir_100_act_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://mobile_manipulator/mesh/mir100/visual/wheel.stl" />
          </geometry>
          <xacro:insert_block name="material_dark_grey" />
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://mobile_manipulator/mesh/mir100/visual/wheel.stl" />
          </geometry>
        </collision>
      </link>

      <gazebo reference="MiR_${locationprefix}_wheel_link">
        <material>Gazebo/DarkGrey</material>
      </gazebo>

    </xacro:macro>

    <xacro:macro name="caster_wheel" params="locationprefix locationright wheel_base_dx">
     
      <!-- caster hub -->

        <joint name="MiR__base_${locationprefix}_caster_rotation_joint" type="continuous">
          <origin xyz="${wheel_base_dx} ${-mir_100_caster_wheel_base_dy * locationright} ${mir_100_caster_wheel_base_dz}" rpy="0 0 0" />
          <parent link="MiR_base_link" />
          <child link="MiR_${locationprefix}_caster_rotation_link" />
          <axis xyz="0 0 1" />
          <dynamics damping="0.01" friction="0.0"/>
        </joint>

        <link name="MiR_${locationprefix}_caster_rotation_link">
          <inertial>
            <!-- <origin xyz="0 0 -0.042500000044" rpy="${0.5 * pi} ${24 * deg_to_rad} ${1.5 * pi}" /> -->
            <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
            <mass value="0.3097539019" />
            <inertia
              ixx="0.0005844517978"
              ixy="0"
              ixz="0"
              iyy="0.00052872551237"
              iyz="0"
              izz="0.00017923555074" />
          </inertial>
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <mesh filename="package://mobile_manipulator/mesh/mir100/visual/caster_wheel_base.stl" />
            </geometry>
            <xacro:insert_block name="material_silver" />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <mesh filename="package://mobile_manipulator/mesh/mir100/collision/caster_wheel_base.stl" />
            </geometry>
          </collision>
        </link>

        <gazebo reference="MiR_${locationprefix}_caster_rotation_link">
          <material>Gazebo/Grey</material>
        </gazebo>

      <!-- caster wheel -->

        <joint name="MiR__base_${locationprefix}_caster_wheel_joint" type="continuous">
          <origin xyz="${mir_100_caster_wheel_dx} ${-mir_100_caster_wheel_dy * locationright} ${mir_100_caster_wheel_dz}" rpy="0 0 0" />
          <parent link="MiR_${locationprefix}_caster_rotation_link" />
          <child link="MiR_${locationprefix}_caster_wheel_link" />
          <axis xyz="0 1 0" />
        </joint>

        <link name="MiR_${locationprefix}_caster_wheel_link">
          <xacro:cylinder_inertial mass="${mir_100_caster_wheel_mass}" radius="${mir_100_caster_wheel_radius}" length="${mir_100_caster_wheel_width}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
          </xacro:cylinder_inertial>
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <mesh filename="package://mobile_manipulator/mesh/mir100/visual/wheel.stl" />
            </geometry>
            <xacro:insert_block name="material_dark_grey" />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <mesh filename="package://mobile_manipulator/mesh/mir100/visual/wheel.stl" />
            </geometry>
          </collision>
        </link>

        <gazebo reference="MiR_${locationprefix}_caster_wheel_link">
          <material>Gazebo/DarkGrey</material>
        </gazebo>

    </xacro:macro>

  <!-- ################################ -->
  <!-- ############### MiR ############ -->

<!-- ######################################### -->
<!-- ################# Macros ################ -->


<!-- #################### MiR #################### -->
<!-- ############################################# -->
  
  <link name="MiR_footprint" />

  <joint name="MiR__footprint_to_base_joint" type="fixed">
    <parent link="MiR_footprint" />
    <child link="MiR_base_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <link name="MiR_base_link">
    <xacro:box_inertial mass="${mir_100_base_mass}" x="0.9" y="0.58" z="0.3">
      <origin xyz="${mir_100_act_wheel_dx} 0 0.20" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="${mir_100_act_wheel_dx} 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/mir100/visual/mir_100_base.stl" />
      </geometry>
      <xacro:insert_block name="material_white" />
    </visual>
    <collision>
      <origin xyz="${mir_100_act_wheel_dx} 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/mir100/collision/mir_100_base.stl" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="MiR_base_link">
    <material>Gazebo/White</material>
  </gazebo>

    <!-- wheels -->
      <xacro:actuated_wheel locationprefix="left" locationright="-1"/>
      <xacro:actuated_wheel locationprefix="right" locationright="1"/>
      <xacro:caster_wheel locationprefix="fl" locationright="-1" wheel_base_dx="${mir_100_front_caster_wheel_base_dx}"/>
      <xacro:caster_wheel locationprefix="fr" locationright="1" wheel_base_dx="${mir_100_front_caster_wheel_base_dx}"/>
      <xacro:caster_wheel locationprefix="bl" locationright="-1" wheel_base_dx="${mir_100_back_caster_wheel_base_dx}"/>
      <xacro:caster_wheel locationprefix="br" locationright="1" wheel_base_dx="${mir_100_back_caster_wheel_base_dx}"/>
    
      <xacro:MiR_wheel_transmissions/>\

      <xacro:set_all_wheel_frictions/>

    <!-- This is a plugin to publish the real pose of the footprint of the mobile robots.
      However, having it causes the crash while using rqt to move the manipulator the error is
        terminate called after throwing an instance of 'std::runtime_error'
        what():  Duration is out of dual 32-bit range
        Aborted (core dumped) 
    
    TODO: Find the csause of the error and fix it.
    --> <!--xacro:p3d_base_controller/-->
    
    <joint name="MiR__base_to_surface_joint" type="fixed">
      <origin xyz="${mir_100_act_wheel_dx} 0 0.352" rpy="0 0 0" />
      <parent link="MiR_base_link" />
      <child link="MiR_surface" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="MiR_surface"/>

  <!-- IMU -->

    <joint name="MiR__base_to_imu_joint" type="fixed">
      <parent link="MiR_base_link" />
      <child link="MiR_imu_link" />
      <origin xyz="0.0 0.0 0.25" rpy="0 0 0" />  <!-- same as real MiR -->
    </joint>

    <link name="MiR_imu_link" />

    <xacro:imu link="MiR_imu_link" imu_topic="Mir/imu_data" update_rate="${imu_update_rate}" stdev="${imu_stdev}" />

    <!-- Create an alias for imu_link. This is necessary because the real MiR's
          TF has imu_link, but the imu_data topic is published in the imu_frame
          frame. -->
      <joint name="MiR__imu_link_to_imu_frame_joint" type="fixed">
        <parent link="MiR_imu_link" />
        <child link="MiR_imu_frame" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </joint>

      <link name="MiR_imu_frame" />

  <!-- Laser scanners -->

    <joint name="MiR__base_to_front_laser_joint" type="fixed">
      <parent link="MiR_base_link" />
      <child link="MiR_front_laser_link" />
      <origin xyz="0.4288 0.2358 0.1914" rpy="0.0 0.0 ${0.25 * pi}" />  <!-- from visually matching up the meshes of the MiR and the laser scanner -->
    </joint>
    
    <xacro:sick_s300 link="MiR_front_laser_link" topic="Mir/back_lscan" />

    <joint name="Mir__base_to_back_laser_joint" type="fixed">
      <parent link="MiR_base_link" />
      <child link="MiR_back_laser_link" />
      <origin xyz="-0.3548 -0.2352 0.1914" rpy="0.0 0.0 ${-0.75 * pi}" />  <!-- from visually matching up the meshes of the MiR and the laser scanner -->
    </joint>

    <xacro:sick_s300 link="MiR_back_laser_link" topic="Mir/back_lscan" />

  <!-- Ultrasound sensors -->

    <link name="MiR_right_us_frame" />

    <joint name="MiR__base_to_right_us_joint" type="fixed">   <!-- right ultrasound -->
      <parent link="MiR_base_link" />
      <child link="MiR_right_us_frame" />
      <origin xyz="0.45 -0.12 0.16 " rpy="0 0 0" />  <!-- from visually matching to the mesh of the MiR -->
    </joint>

    <xacro:ultrasound_gazebo link="MiR_right_us_frame" topic="/MiR/right_ultrasound" update_rate="5" 
                                                  range_min="0.01" range_max="0.75"
                                                  horizental_min_angle="-0.25" horizental_max_angle="0.25"
                                                  vertical_min_angle="-0.25" vertical_max_angle="0.25"/>

    <link name="MiR_left_us_frame" />

    <joint name="MiR__base_to_left_us_joint" type="fixed">   <!-- right ultrasound -->
      <parent link="MiR_base_link" />
      <child link="MiR_left_us_frame" />
      <origin xyz="0.45 -0.12 0.16 " rpy="0 0 0" />  <!-- from visually matching to the mesh of the MiR -->
    </joint>

    <xacro:ultrasound_gazebo link="MiR_left_us_frame" topic="/MiR/left_ultrasound" update_rate="10" 
                                                  range_min="0.01" range_max="0.75"
                                                  horizental_min_angle="-0.25" horizental_max_angle="0.25"
                                                  vertical_min_angle="-0.25" vertical_max_angle="0.25"/>


<!-- ############################################# -->
<!-- #################### MiR #################### -->

<!-- #################### UR10 ################### -->
<!-- ############################################# -->

  <link name="UR10_base_link" >
    <visual>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/visual/base.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/collision/base.stl"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${ur10_base_mass}">
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="UR10_base_link">
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="UR10__base_to_shoulder_pan_joint" type="revolute">
    <parent link="UR10_base_link" />
    <child link = "UR10_shoulder_pan_link" />
    <origin xyz="0.0 0.0 ${ur10_shoulder_height}" rpy="0.0 0.0 0.0" />
    <axis xyz="0 0 1" />
    <limit lower="${ur10_shoulder_pan_lower_limit}" upper="${ur10_shoulder_pan_upper_limit}" effort="330.0" velocity="2.16"/>
    <xacro:if value="${ur10_safety_limits}">
      <safety_controller soft_lower_limit="${ur10_shoulder_pan_lower_limit + ur10_safety_pos_margin}" soft_upper_limit="${ur10_shoulder_pan_upper_limit - ur10_safety_pos_margin}" k_position="${ur10_safety_k_position}" k_velocity="0.0"/>
    </xacro:if>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="UR10_shoulder_pan_link">
    <visual>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/visual/shoulder.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/collision/shoulder.stl"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${ur10_shoulder_mass}">
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="UR10_shoulder_pan_link">
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="UR10__shoulder_pan_to_upper_arm_joint" type="revolute">
    <parent link="UR10_shoulder_pan_link" />
    <child link = "UR10_upper_arm_link" />
    <origin xyz="0.0 ${ur10_shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />
    <axis xyz="0 1 0" />
    <limit lower="${ur10_shoulder_lift_lower_limit}" upper="${ur10_shoulder_lift_upper_limit}" effort="330.0" velocity="2.16"/>
    <xacro:if value="${ur10_safety_limits}">
      <safety_controller soft_lower_limit="${ur10_shoulder_lift_lower_limit + ur10_safety_pos_margin}" soft_upper_limit="${ur10_shoulder_lift_upper_limit - ur10_safety_pos_margin}" k_position="${ur10_safety_k_position}" k_velocity="0.0"/>
    </xacro:if>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="UR10_upper_arm_link">
    <visual>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/visual/upperarm.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/collision/upperarm.stl"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertial radius="0.075" length="${-a2}" mass="${ur10_upper_arm_mass}">
      <origin xyz="0.0 ${-ur10_upper_arm_inertia_offset} ${-a2/2.0}" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="UR10_upper_arm_link">
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="UR10__upper_arm_to_fore_arm_joint" type="revolute">
    <parent link="UR10_upper_arm_link" />
    <child link = "UR10_fore_arm_link" />
    <origin xyz="0.0 ${ur10_elbow_offset} ${ur10_upper_arm_length}" rpy="0.0 0.0 0.0" />
    <axis xyz="0 1 0" />
    <limit lower="${ur10_elbow_joint_lower_limit}" upper="${ur10_elbow_joint_upper_limit}" effort="150.0" velocity="3.15"/>
    <xacro:if value="${ur10_safety_limits}">
      <safety_controller soft_lower_limit="${ur10_elbow_joint_lower_limit + ur10_safety_pos_margin}" soft_upper_limit="${ur10_elbow_joint_upper_limit - ur10_safety_pos_margin}" k_position="${ur10_safety_k_position}" k_velocity="0.0"/>
    </xacro:if>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="UR10_fore_arm_link">
    <visual>
        <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/visual/forearm.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/collision/forearm.stl"/>
      </geometry>
    </collision>
    <gazebo>
      <selfCollide>true</selfCollide>
    </gazebo>
    <xacro:cylinder_inertial radius="0.075" length="${-a3}" mass="${ur10_forearm_mass}">
      <origin xyz="0.0 0.0 ${-a3/2.0}" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="UR10_fore_arm_link">
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="UR10__fore_arm_to_wrist_1_joint" type="revolute">
    <parent link="UR10_fore_arm_link" />
    <child link = "UR10_wrist_1_link" />
    <origin xyz="0.0 0.0 ${ur10_forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
    <axis xyz="0 1 0" />
    <limit lower="${ur10_wrist_1_lower_limit}" upper="${ur10_wrist_1_upper_limit}" effort="54.0" velocity="3.2"/>
    <xacro:if value="${ur10_safety_limits}">
      <safety_controller soft_lower_limit="${ur10_wrist_1_lower_limit + ur10_safety_pos_margin}" soft_upper_limit="${ur10_wrist_1_upper_limit - ur10_safety_pos_margin}" k_position="${ur10_safety_k_position}" k_velocity="0.0"/>
    </xacro:if>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="UR10_wrist_1_link">
    <visual>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/visual/wrist1.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/collision/wrist1.stl"/>
      </geometry>
    </collision>
    <gazebo>
      <selfCollide>true</selfCollide>
    </gazebo>
    <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${ur10_wrist_1_mass}">
      <origin xyz="0.0 ${ur10_wrist_1_length} 0.0" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="UR10_wrist_1_link">
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="UR10__wrist_1_to_wrist_2_joint" type="revolute">
    <parent link="UR10_wrist_1_link" />
    <child link = "UR10_wrist_2_link" />
    <origin xyz="0.0 ${ur10_wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
    <axis xyz="0 0 1" />
    <limit lower="${ur10_wrist_2_lower_limit}" upper="${ur10_wrist_2_upper_limit}" effort="54.0" velocity="3.2"/>
    <xacro:if value="${ur10_safety_limits}">
      <safety_controller soft_lower_limit="${ur10_wrist_2_lower_limit + ur10_safety_pos_margin}" soft_upper_limit="${ur10_wrist_2_upper_limit - ur10_safety_pos_margin}" k_position="${ur10_safety_k_position}" k_velocity="0.0"/>
    </xacro:if>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="UR10_wrist_2_link">
    <visual>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/visual/wrist2.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/collision/wrist2.stl"/>
      </geometry>
    </collision>
    <gazebo>
      <selfCollide>true</selfCollide>
    </gazebo>
    <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${ur10_wrist_2_mass}">
      <origin xyz="0.0 0.0 ${ur10_wrist_2_length}" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="UR10_wrist_2_link">
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="UR10__wrist_2_to_wrist_3_joint" type="revolute">
    <parent link="UR10_wrist_2_link" />
    <child link = "UR10_wrist_3_link" />
    <origin xyz="0.0 0.0 ${ur10_wrist_2_length}" rpy="0.0 0.0 0.0" />
    <axis xyz="0 1 0" />
    <limit lower="${ur10_wrist_3_lower_limit}" upper="${ur10_wrist_3_upper_limit}" effort="54.0" velocity="3.2"/>
    <xacro:if value="${ur10_safety_limits}">
      <safety_controller soft_lower_limit="${ur10_wrist_3_lower_limit + ur10_safety_pos_margin}" soft_upper_limit="${ur10_wrist_3_upper_limit - ur10_safety_pos_margin}" k_position="${ur10_safety_k_position}" k_velocity="0.0"/>
    </xacro:if>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="UR10_wrist_3_link">
    <visual>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/visual/wrist3.dae"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mobile_manipulator/mesh/ur10/collision/wrist3.stl"/>
      </geometry>
    </collision>
    <gazebo>
      <selfCollide>true</selfCollide>
    </gazebo>
    <xacro:cylinder_inertial radius="0.045" length="0.0305" mass="${ur10_wrist_3_mass}">
      <origin xyz="0.0 ${ur10_wrist_3_length - 0.0305/2} 0.0" rpy="${pi/2} 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="UR10_wrist_3_link">
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="UR10__wrist_3_to_end_effector_fixed_joint" type="fixed">
    <parent link="UR10_wrist_3_link" />
    <child link = "UR10_end_effector_link" />
    <origin xyz="0.0 ${ur10_wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
  </joint>

  <link name="UR10_end_effector_link">
    <collision>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.01 0 0"/>
    </collision>
    <gazebo>
      <selfCollide>true</selfCollide>
    </gazebo>
  </link>


  <xacro:UR10_joint_transmissions/>

<!-- ############################################# -->
<!-- #################### UR10 ################### -->

<!-- ********************************** -->
<!-- UR10 Arm connection to Mobile Base -->
  <joint name="UR10_base_to_MiR_base_joint" type="fixed">
      <origin xyz="0.15 0.0 0.352" rpy="0.0 0.0 0.0" />
      <parent link="MiR_base_link"/>
      <child link="UR10_base_link"/>
  </joint>
<!-- UR10 Arm connection to Mobile Base -->
<!-- ********************************** -->

<!-- #################### Barret Hand ################### -->
<!-- #################################################### -->

  <link name="BH282_base_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 0" />
      <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="1.0"  iyz="0.0"  izz="1.0" />
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
        <mesh filename="package://mobile_manipulator/mesh/barret/palm_282.dae"/>
        </geometry>
        <color rgba="0.75 0.75 0.75 1.0"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry>
        <mesh filename="package://mobile_manipulator/mesh/barret/palm_282.dae"/>
        </geometry>
        <contact_coefficients kd="1.0" kp="1000.0" mu="0"/>
    </collision>     
  </link>
  <gazebo reference="BH282_base_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- Finger 1-->

		<link name="BH282_finger_11_link">
			<inertial>
			  <mass value="0.1"/>
			  <origin xyz="-0.046 0 0" rpy="0 0 0"/>
			  <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
			</inertial>
			<visual>
			  <origin xyz="0 0 0" rpy="0 0 0" />
			  <geometry>
				 <mesh filename="package://mobile_manipulator/mesh/barret/knuckle.dae" />
			  </geometry>
			</visual>
			<collision>
			  <origin xyz="0 0 0" rpy="0 0 0" />
			  <geometry>
				<mesh filename="package://mobile_manipulator/mesh/barret/knuckle.dae" />
			  </geometry>
			</collision>
		</link>
    <gazebo reference="BH282_finger_11_link">
      <material>Gazebo/White</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

		<joint name="BH282__base_to_finger_11_joint" type="revolute">
			<parent link="BH282_base_link"/>
			<child link="BH282_finger_11_link"/>
			<origin xyz="-0.025 0 0.0252" rpy="0 0 1.5708" />
			<axis xyz="0 0 -1"/>
			<limit effort="${BH282_joint_effort_limit}" lower="0" upper="${pi}" velocity="${BH282_joint_velocity_limit}"/>
			<dynamics damping="${BH282_joint_damping}" friction="${BH282_joint_friction}"/>
		</joint>
    <xacro:BH282_joint_transmission joint="base_to_finger_11"/>

		<link name="BH282_finger_12_link">
			 <inertial>
				<mass value="0.1"/>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
			 </inertial>
			 <visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
				  <mesh filename="package://mobile_manipulator/mesh/barret/finger.dae" />
				</geometry>
			 </visual>		
			 <collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
				  <mesh filename="package://mobile_manipulator/mesh/barret/finger.dae" />
				</geometry>
				<contact_coefficients kd="1.0" kp="1000.0" mu="0"/>
			 </collision>
		</link>
    <gazebo reference="BH282_finger_12_link">
      <material>Gazebo/White</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

		<joint name="BH282__finger_11_to_finger_12_joint" type="revolute">
			<parent link="BH282_finger_11_link"/>
			<child link="BH282_finger_12_link"/>
			<origin	xyz="-0.05 0 0.0339"
				rpy="${0.5 * pi} 0 0" />
			<axis xyz="0 0 -1"/>
			<limit effort="${BH282_joint_effort_limit}" lower="0.0" upper="2.44" velocity="${BH282_joint_velocity_limit}"/>
			<dynamics damping="${BH282_joint_damping}" friction="${BH282_joint_friction}"/>
		</joint>
    <xacro:BH282_joint_transmission joint="finger_11_to_finger_12"/>

		<link name="BH282_finger_13_link">
		 <inertial>
			<mass value="0.1"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
		 </inertial>
		 <visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
			  <mesh filename="package://mobile_manipulator/mesh/barret/finger_tip.dae" />
			</geometry>
		 </visual>		
		 <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
			  <mesh filename="package://mobile_manipulator/mesh/barret/finger_tip.dae" />
			</geometry>
			<contact_coefficients kd="1.0" kp="1000.0" mu="0"/>
		 </collision>
		</link>
    <gazebo reference="BH282_finger_13_link">
      <material>Gazebo/White</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>
    
		<joint name="BH282__finger_12_to_finger_13_joint" type="revolute">
			<parent link="BH282_finger_12_link"/>
			<child link="BH282_finger_13_link"/>
			<origin xyz="-0.069936 0.003 0" rpy="0 0 0" />
			<axis xyz="0 0 -1"/>
			<limit effort="${BH282_joint_effort_limit}" lower="0.0" upper="0.84" velocity="${BH282_joint_velocity_limit}"/>
			<dynamics damping="${BH282_joint_damping}" friction="${BH282_joint_friction}"/>
		</joint>
    <xacro:BH282_joint_transmission joint="finger_12_to_finger_13"/>


  <!-- Finger 2-->

		<link name="BH282_finger_21_link">
			<inertial>
			  <mass value="0.1"/>
			  <origin xyz="-0.046 0 0" rpy="0 0 0"/>
			  <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
			</inertial>
			<visual>
			  <origin xyz="0 0 0" rpy="0 0 0" />
			  <geometry>
				 <mesh filename="package://mobile_manipulator/mesh/barret/knuckle.dae" />
			  </geometry>
			</visual>
			<collision>
			  <origin xyz="0 0 0" rpy="0 0 0" />
			  <geometry>
				<mesh filename="package://mobile_manipulator/mesh/barret/knuckle.dae" />
			  </geometry>
			</collision>
		</link>
    <gazebo reference="BH282_finger_21_link">
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="BH282__base_to_finger_21_joint" type="revolute">
			<parent link="BH282_base_link"/>
			<child link="BH282_finger_21_link"/>
			<origin xyz="0.025 0 0.0252" rpy="0 0 ${0.5 * pi}" />
			<axis xyz="0 0 1"/>
			<limit effort="${BH282_joint_effort_limit}" lower="0" upper="${pi}" velocity="${BH282_joint_velocity_limit}"/>
			<dynamics damping="${BH282_joint_damping}" friction="${BH282_joint_friction}"/>
		</joint>
    <xacro:BH282_joint_transmission joint="base_to_finger_21"/>

		<link name="BH282_finger_22_link">
			 <inertial>
				<mass value="0.1"/>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
			 </inertial>
			 <visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
				  <mesh filename="package://mobile_manipulator/mesh/barret/finger.dae" />
				</geometry>
			 </visual>		
			 <collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
				  <mesh filename="package://mobile_manipulator/mesh/barret/finger.dae" />
				</geometry>
				<contact_coefficients kd="1.0" kp="1000.0" mu="0"/>
			 </collision>
		</link>
    <gazebo reference="BH282_finger_22_link">
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

		<joint name="BH282__finger_21_to_finger_22_joint" type="revolute">
			<parent link="BH282_finger_21_link"/>
			<child link="BH282_finger_22_link"/>
			<origin	xyz="-0.05 0 0.0339"
				rpy="${0.5 * pi} -8.8281E-17 0" />
			<axis xyz="0 0 -1"/>
			<limit effort="${BH282_joint_effort_limit}" lower="0.0" upper="2.44" velocity="${BH282_joint_velocity_limit}"/>
			<dynamics damping="${BH282_joint_damping}" friction="${BH282_joint_friction}"/>
		</joint>
    <xacro:BH282_joint_transmission joint="finger_21_to_finger_22"/>

		<link name="BH282_finger_23_link">
		 <inertial>
			<mass value="0.1"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
		 </inertial>
		 <visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
			  <mesh filename="package://mobile_manipulator/mesh/barret/finger_tip.dae" />
			</geometry>
		 </visual>		
		 <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
			  <mesh filename="package://mobile_manipulator/mesh/barret/finger_tip.dae" />
			</geometry>
			<contact_coefficients kd="1.0" kp="1000.0" mu="0"/>
		 </collision>
		</link>
    <gazebo reference="BH282_finger_23_link">
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

		<joint name="BH282__finger_22_to_finger_23_joint" type="revolute">
			<parent link="BH282_finger_22_link"/>
			<child link="BH282_finger_23_link"/>
			<origin xyz="-0.069936 0.003 0" rpy="0 0 0" />
			<axis xyz="0 0 -1"/>
			<limit effort="${BH282_joint_effort_limit}" lower="0.0" upper="0.84" velocity="${BH282_joint_velocity_limit}"/>
			<dynamics damping="${BH282_joint_damping}" friction="${BH282_joint_friction}"/>
		</joint>
    <xacro:BH282_joint_transmission joint="finger_22_to_finger_23"/>

  <!-- Finger 3-->

    <link name="BH282_finger_31_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="-0.046 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
      <visual>
        <origin xyz="-0.04 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/mesh/barret/knuckle_fixed.dae" />
        </geometry>
      </visual>		
      <collision>
        <origin xyz="-0.04 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/mesh/barret/knuckle_fixed.dae" />
        </geometry>
        <contact_coefficients kd="1.0" kp="1000.0" mu="0"/>
      </collision>
    </link>
    <gazebo reference="BH282_finger_31_link">
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="BH282__base_to_finger_31_joint" type="fixed">
      <parent link="BH282_base_link"/>
      <child link="BH282_finger_31_link"/>
      <origin xyz="0 0 0.0252" rpy="0 0 ${-0.5 * pi}"/>
    </joint>

    <link name="BH282_finger_32_link">
        <inertial>
          <mass value="0.1"/>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://mobile_manipulator/mesh/barret/finger.dae" />
          </geometry>
        </visual>		
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://mobile_manipulator/mesh/barret/finger.dae" />
          </geometry>
          <contact_coefficients kd="1.0" kp="1000.0" mu="0"/>
        </collision>
    </link>
    <gazebo reference="BH282_finger_32_link">
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="BH282__finger_31_to_finger_32_joint" type="revolute">
      <parent link="BH282_finger_31_link"/>
      <child link="BH282_finger_32_link"/>
      <origin	xyz="-0.05 0 0.0339"
        rpy="${0.5 * pi} -8.8281E-17 0" />
      <axis xyz="0 0 -1"/>
      <limit effort="${BH282_joint_effort_limit}" lower="0.0" upper="2.44" velocity="${BH282_joint_velocity_limit}"/>
      <dynamics damping="${BH282_joint_damping}" friction="${BH282_joint_friction}"/>
    </joint>
    <xacro:BH282_joint_transmission joint="finger_31_to_finger_32"/>

    <link name="BH282_finger_33_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/mesh/barret/finger_tip.dae" />
        </geometry>
      </visual>		
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/mesh/barret/finger_tip.dae" />
        </geometry>
        <contact_coefficients kd="1.0" kp="1000.0" mu="0"/>
      </collision>
    </link>
    <gazebo reference="BH282_finger_33_link">
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="BH282__finger_32_to_finger_33_joint" type="revolute">
      <parent link="BH282_finger_32_link"/>
      <child link="BH282_finger_33_link"/>
      <origin xyz="-0.069936 0.003 0" rpy="0 0 0" />
      <axis xyz="0 0 -1"/>
      <limit effort="${BH282_joint_effort_limit}" lower="0.0" upper="0.84" velocity="${BH282_joint_velocity_limit}"/>
      <dynamics damping="${BH282_joint_damping}" friction="${BH282_joint_friction}"/>
    </joint>
    <xacro:BH282_joint_transmission joint="finger_32_to_finger_33"/>


<!-- #################################################### -->
<!-- #################### Barret Hand ################### -->

<!-- ******************************** -->
<!-- Barrett Haand connection to UR10 -->
  <joint name="BH282_base_to_end_effector_joint" type="fixed">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 ${0.5 * pi} 0.0" />
      <parent link="UR10_end_effector_link"/>
      <child link="BH282_base_link"/>
  </joint>
<!-- Barrett Haand connection to UR10 -->
<!-- ******************************** -->


</robot>