ur10_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - UR10__base_to_shoulder_pan_joint
     - UR10__shoulder_pan_to_upper_arm_joint
     - UR10__upper_arm_to_fore_arm_joint
     - UR10__fore_arm_to_wrist_1_joint
     - UR10__wrist_1_to_wrist_2_joint
     - UR10__wrist_2_to_wrist_3_joint
  constraints:
    # If the time stamp of the target trajectory point is t, then if the target is reached within t +/-goal_time, 
    # the trajectory is successful, otherwise it is aborted.
    goal_time: 0.00
    # The speed is considered to be approximately equal to zero.
    stopped_velocity_tolerance: 0.00
    UR10__base_to_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    UR10__shoulder_pan_to_upper_arm_joint: {trajectory: 0.1, goal: 0.1}
    UR10__upper_arm_to_fore_arm_joint: {trajectory: 0.1, goal: 0.1}
    UR10__fore_arm_to_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    UR10__wrist_1_to_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    UR10__wrist_2_to_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.00
  # The frequency (in Hz) of the controller status release.
  state_publish_rate:  25
  # Frequency (in Hz) monitors the frequency of the action target state. This is an advanced parameter that does not need to be changed.
  action_monitor_rate: 10
